const data = {
  products: [
    {
      _id: 1,
      name: "Shirt",
      category: "Shirts",
      image: "/images/shirt.png",
      price: "60",
      brand: "Calvin Klein",
      rating: 4.5,
      countInStock: 6,
    },
    {
      _id: 2,
      name: "Sneakers",
      category: "Shirts",
      image: "/images/shoes.png",
      price: "80",
      brand: "Nike",
      rating: 4.5,
      countInStock: 3,
    },
    {
      _id: 3,
      name: "Blazer",
      category: "Blazer",
      image: "/images/blazer.png",
      price: "110",
      brand: "Hilfiger",
      rating: 4.5,
      countInStock: 0,
    },
    {
      _id: 4,
      name: "Pants",
      category: "Pants",
      image: "/images/pants.png",
      price: "45",
      brand: "NewYorker",
      rating: 4.5,
      countInStock: 2,
    },

    {
      _id: 5,
      name: "Watches",
      category: "Watches",
      image: "/images/watches.png",
      price: "300",
      brand: "Tissot",
      rating: 4.5,
      countInStock: 7,
    },
    {
      _id: 6,
      name: "Tie",
      category: "Ties",
      image: "/images/tie.png",
      price: "20",
      brand: "Pull&Bear",
      rating: 4.5,
      countInStock: 18,
    },
    {
      _id: 7,
      name: "Headphones",
      category: "Headphones",
      image: "/images/headphones.png",
      price: "260",
      brand: "Xiaomi",
      rating: 4.5,
      countInStock: 18,
    },
    {
      _id: 8,
      name: "Gloves",
      category: "Gloves",
      image: "/images/gloves.png",
      price: "45",
      brand: "Bally",
      rating: 4.5,
      countInStock: 18,
    },
    {
      _id: 9,
      name: "Ring",
      category: "Ring",
      image: "/images/ring.png",
      price: "45",
      brand: "Bryan Anthony's",
      rating: 4.5,
      countInStock: 18,
    },
  ],
};

export default data;
